### ISSUE TITLE
OSError: libcudart.so.8.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by joel5638** [RussellSB/automated-gait-analysis#1]
trying to run 

python3 pose_estimation.py.
added my video in the cv2.capture. and i get this error

/usr/lib/python3/dist-packages/apport/report.py:13: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import fnmatch, glob, traceback, errno, sys, atexit, locale, imp
Traceback (most recent call last):
  File "pose_estimation.py", line 14, in <module>
    from gluoncv.data.transforms.pose import detector_to_alpha_pose, heatmap_to_coord_alpha_pose
  File "/usr/local/lib/python3.6/dist-packages/gluoncv/__init__.py", line 8, in <module>
    from .utils.version import _require_mxnet_version, _deprecate_python2
  File "/usr/local/lib/python3.6/dist-packages/gluoncv/utils/__init__.py", line 6, in <module>
    from . import viz
  File "/usr/local/lib/python3.6/dist-packages/gluoncv/utils/viz/__init__.py", line 4, in <module>
    from .image import plot_image, cv_plot_image
  File "/usr/local/lib/python3.6/dist-packages/gluoncv/utils/viz/image.py", line 3, in <module>
    import mxnet as mx
  File "/usr/local/lib/python3.6/dist-packages/mxnet/__init__.py", line 25, in <module>
    from . import engine
  File "/usr/local/lib/python3.6/dist-packages/mxnet/engine.py", line 23, in <module>
    from .base import _LIB, check_call
  File "/usr/local/lib/python3.6/dist-packages/mxnet/base.py", line 111, in <module>
    _LIB = _load_lib()
  File "/usr/local/lib/python3.6/dist-packages/mxnet/base.py", line 103, in _load_lib
    lib = ctypes.CDLL(lib_path[0], ctypes.RTLD_LOCAL)
  File "/usr/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libcudart.so.8.0: cannot open shared object file: No such file or directory

**Comment by RussellSB** [comment]
Excuse the late reply! For the object detection part of my pipeline (for person detection), I used GluonCV's release of YOLOv3 with GPU specified.

Since its mentioning libcudart.so.8.0 on the last line of the error I suspect its a GPU issue.

I think this could either be fixed by:
- Setting up GPU support for such applications on your PC (i.e. install CUDA, and the CUDA version of gluoncv)
- Reinstalling GluonCV with GPU not included. Editing the code in pose_estimation.py - line 29, remove and line 30, remove the ctx argument
